proy_lab/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.views import *
from laboratorio.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('laboratorio/', include('laboratorio.urls')),
]

proy_lab/laboratorio/urls.py
from django.urls import path
from laboratorio.views import *
from . import views

urlpatterns = [
    path('', index, name='index'),
    path("laboratorios/", laboratorio_list, name="laboratorio_list"),
    path('laboratorios/crear/', laboratorio_create, name='laboratorio_create'),
    path("laboratorios/editar/<int:pk>/", laboratorio_update, name="laboratorio_update"),
    path("laboratorios/eliminar/<int:pk>/", laboratorio_delete, name="laboratorio_delete"),
]

proy_lab/laboratorio/models.py
from django.db import models
from django.core.exceptions import ValidationError
from datetime import date

class Laboratorio(models.Model):
    nombre = models.CharField(max_length=255)
    ciudad = models.CharField(max_length=255, null=True, blank=True)
    pais = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.nombre

class DirectorGeneral(models.Model):
    nombre = models.CharField(max_length=255)
    especialidad = models.CharField(max_length=255, null=True, blank=True)
    laboratorio = models.OneToOneField(Laboratorio, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


def validar_fecha_fabricacion(value):
    if value.year < 2015:
        raise ValidationError("La fecha de fabricación no puede ser anterior a 2015.")

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    laboratorio = models.ForeignKey(Laboratorio, on_delete=models.CASCADE)
    f_fabricacion = models.DateField(validators=[validar_fecha_fabricacion])
    p_costo = models.DecimalField(max_digits=12, decimal_places=2)
    p_venta = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return f"{self.nombre} ({self.laboratorio.nombre})"

proy_lab/laboratorio/forms.py
from django import forms
from .models import Laboratorio

class LaboratorioFormCreate(forms.ModelForm):
    class Meta:
        model = Laboratorio
        fields = ["nombre", "ciudad", "pais"]

class LaboratorioFormUpdate(forms.ModelForm):
    class Meta:
        model = Laboratorio
        fields = ["nombre", "ciudad", "pais"]

proy_lab/laboratorio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Laboratorio
from .forms import LaboratorioFormCreate, LaboratorioFormUpdate

# Create your views here.
def index(request):
    return render(request, 'index.html')


#CREATE LABS
def laboratorio_create(request):
    if request.method == "POST":
        form = LaboratorioFormCreate(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("laboratorio_list"))
    else:
        form = LaboratorioFormCreate()
    return render(request, "laboratorio/laboratorio_form_create.html", {"form": form})


#READ LABS (LISTAR)
def laboratorio_list(request):
    laboratorios = Laboratorio.objects.all().order_by("id")
    return render(request, "laboratorio/laboratorio_list.html", {"laboratorios": laboratorios})


#UPDATE LABS
def laboratorio_update(request, pk):
    laboratorio = get_object_or_404(Laboratorio, pk=pk)
    if request.method == "POST":
        form = LaboratorioFormUpdate(request.POST, instance=laboratorio)
        if form.is_valid():
            form.save()
            return redirect(reverse("laboratorio_list"))
    else:
        form = LaboratorioFormUpdate(instance=laboratorio)
    return render(request, "laboratorio/laboratorio_form_update.html", {"form": form})


#DELETE LABS
def laboratorio_delete(request, pk):
    laboratorio = get_object_or_404(Laboratorio, pk=pk)
    if request.method == "POST":
        laboratorio.delete()
        return redirect(reverse("laboratorio_list"))
    return render(request, "laboratorio/laboratorio_confirm_delete.html", {"laboratorio": laboratorio})

proy_lab/laboratorio/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock  %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

</head>

<body>
    {% include 'navbar.html' %}

    
    {% block content %}
    {% endblock  %}


    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    
</body>

</html>

proy_lab/laboratorio/templates/footer.html
<div class="footer bg-dark text-white py-3 mt-5">
    <div class="container text-center">
        <p class="mb-0">M7 Final Drilling - Bootcamp Full Stack Python | Irina Serey </p>
        <p class="mb-0">Todos los derechos reservados</p>
    </div>
</div>

proy_lab/laboratorio/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-1">
    <h1 class="text-center mb-4">Bienvenido a la Plataforma de Gestión de Laboratorios</h1>
    
    <div class="alert alert-info">
        <h4>Bienvenido</h4>
        <p>En esta aplicación podrás realizar las siguientes acciones:</p>
    </div>
    
    <ul class="list-group">
        <li class="list-group-item">
            <strong>Crear:</strong> Podrás crear nuevos registros de Laboratorio en Nuevo Lab.
        </li>
        <li class="list-group-item">    
            <strong>Actualizar:</strong> Desde la sección Info Labs podrás editar los atributos de Nombre, Ciudad y País de los Laboratorios registrados.
        </li>
        <li class="list-group-item">
            <strong>Eliminar:</strong> Desde la sección Info Labs podrás eliminar un Laboratorio registrado.
        </li>
        <li class="list-group-item">
            <strong>Acceder al Admin:</strong> Podrás acceder a la consola de administración de Django.
        </li>
    </ul>

    <div class="text-center mt-4">
        <a href="{% url 'laboratorio_list' %}" class="btn btn-info btn-lg ml-3">Info Labs</a>
        <a href="{% url 'laboratorio_create' %}" class="btn btn-primary btn-lg ml-3">Nuevo Lab</a>
        <a href="/admin/" class="btn btn-danger btn-lg ml-3">Administración de Django</a>
    </div>
</div>

{% endblock %}

proy_lab/laboratorio/templates/laboratorio/laboratorio_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Eliminar Laboratorio</h2>
    <p class="text-center mb-4">¿Estás seguro de que deseas eliminar el laboratorio <strong>"{{ laboratorio.nombre }}"</strong>?</p>
    
    <form method="post" class="text-center">
        {% csrf_token %}
        
        <div class="mb-3">
            <button type="submit" class="btn btn-danger btn-lg">Sí, eliminar</button>
        </div>

        <div class="mb-3">
            <a href="{% url 'laboratorio_list' %}" class="btn btn-secondary btn-lg">Cancelar</a>
        </div>
    </form>
</div>
{% endblock %}

proy_lab/laboratorio/templates/laboratorio/laboratorio_form_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Agregar Nuevo Laboratorio</h1>
        
        <form method="post">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                <input type="text" name="nombre" class="form-control" id="id_nombre" value="{{ form.nombre.value }}">
            </div>
            
            <div class="mb-3">
                <label for="id_ciudad" class="form-label">Ciudad</label>
                <input type="text" name="ciudad" class="form-control" id="id_ciudad" value="{{ form.ciudad.value }}">
            </div>
            
            <div class="mb-3">
                <label for="id_pais" class="form-label">País</label>
                <input type="text" name="pais" class="form-control" id="id_pais" value="{{ form.pais.value }}">
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
        
        <a href="{% url 'laboratorio_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
    </div>
{% endblock %}

proy_lab/laboratorio/templates/laboratorio/laboratorio_form_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Actualizar Laboratorio</h1>
        
        <form method="post">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                <input type="text" name="nombre" class="form-control" id="id_nombre" value="{{ form.nombre.value }}">
            </div>
            
            <div class="mb-3">
                <label for="id_ciudad" class="form-label">Ciudad</label>
                <input type="text" name="ciudad" class="form-control" id="id_ciudad" value="{{ form.ciudad.value }}">
            </div>
            
            <div class="mb-3">
                <label for="id_pais" class="form-label">País</label>
                <input type="text" name="pais" class="form-control" id="id_pais" value="{{ form.pais.value }}">
            </div>
        
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </form>
        
        
        <a href="{% url 'laboratorio_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
    </div>


{% endblock %}

proy_lab/laboratorio/templates/laboratorio/laboratorio_list.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <h2 class="text-center mb-4">Lista de Laboratorios</h2>
    
    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Ciudad</th>
                    <th>País</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for laboratorio in laboratorios %}
                <tr>
                    <td>{{ laboratorio.id }}</td>
                    <td>{{ laboratorio.nombre }}</td>
                    <td>{{ laboratorio.ciudad }}</td>
                    <td>{{ laboratorio.pais }}</td>
                    <td>
                        <a href="{% url 'laboratorio_update' laboratorio.id %}" class="btn btn-warning btn-sm">Actualizar</a>
                        <a href="{% url 'laboratorio_delete' laboratorio.id %}" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de eliminar este laboratorio?');">Eliminar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5" class="text-center">No hay laboratorios registrados.</td>
                </tr>
                
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="text-end mt-2">
        <a href="{% url 'laboratorio_create' %}" class="btn btn-primary btn-md">Nuevo Lab</a>
    </div>

</div>

{% endblock %}

proy_lab/laboratorio/templates/navbar.html
<nav class="navbar bg-dark navbar-expand-lg" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Inicio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" 
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav me-auto">
        <a class="nav-link" href="{% url 'laboratorio_list' %}">Info Labs</a>
        <a class="nav-link" href="{% url 'laboratorio_create' %}">Nuevo Lab</a>
      </div>
    </div>
  </div>
</nav>